name: Publish

on: 
  workflow_dispatch:
  push:
    branches:
    - master
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
  
    - name: Restore
      run: dotnet restore ./VisaApp.sln
  
    - name: Build
      run: dotnet build ./VisaApp.sln --configuration Release
  
    - name: Publish
      run: dotnet publish ./Presentation/VisaApp.Api/VisaApp.Api.csproj --configuration Release --no-build --output ./publish

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with: 
        app-name: VisaApp
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_VISAAPP }}
        package: './publish'
